/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StoreBranches } from "./StoreBranches";
import { StoreBranchesCountArgs } from "./StoreBranchesCountArgs";
import { StoreBranchesFindManyArgs } from "./StoreBranchesFindManyArgs";
import { StoreBranchesFindUniqueArgs } from "./StoreBranchesFindUniqueArgs";
import { DeleteStoreBranchesArgs } from "./DeleteStoreBranchesArgs";
import { StoreBranchesService } from "../storeBranches.service";
@graphql.Resolver(() => StoreBranches)
export class StoreBranchesResolverBase {
  constructor(protected readonly service: StoreBranchesService) {}

  async _storeBranchesItemsMeta(
    @graphql.Args() args: StoreBranchesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StoreBranches])
  async storeBranchesItems(
    @graphql.Args() args: StoreBranchesFindManyArgs
  ): Promise<StoreBranches[]> {
    return this.service.storeBranchesItems(args);
  }

  @graphql.Query(() => StoreBranches, { nullable: true })
  async storeBranches(
    @graphql.Args() args: StoreBranchesFindUniqueArgs
  ): Promise<StoreBranches | null> {
    const result = await this.service.storeBranches(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StoreBranches)
  async deleteStoreBranches(
    @graphql.Args() args: DeleteStoreBranchesArgs
  ): Promise<StoreBranches | null> {
    try {
      return await this.service.deleteStoreBranches(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
